### ISSUE TITLE
Overlay data source does not support 'configurations' directive.

### ISSUE THREAD

**Issue by m13t** [kbst/terraform-provider-kustomization#115]
Hi,

I've noticed that the `kustomization_overlay` data source does not support the Kustomize `configurations` directive, which would be used to allow specifying `varReferences`. This is particularly useful as `vars` only works with a subset of native Kubernetes resources out of the box. In order to be able to use `vars` with kinds for things like Istio, we'd need to add a `varReference` spec in a configuration yaml and then specify that in the `configurations` section.

**Comment by pst** [comment]
I just remembered I did not implement `configurations` on purpose, because it's incompatible with plugins. It's also not documented here: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/ So I assume it may be deprecated. I removed the good first issue label accordingly. This would probably require a deeper investigation first.

**Comment by pst** [comment]
Closing this, since there hasn't been any activity for a month.
