### ISSUE TITLE
Proposals for version-less resource IDs

### ISSUE THREAD

**Issue by willthames** [kbst/terraform-provider-kustomization#135]
While #128 proves the concept that we can remove version from resource IDs, as @pst mentions, if we're going to break backwards compatibility by changing resource IDs, we can take that opportunity to go further and provide friendlier IDs.

Good IDs will have some combination of these properties:
* consistent delimiters to make tokenizing the IDs easier
* friendlier to some shells (default zsh on OS X doesn't like square brackets that aren't part of a glob match, but default bash on OS X didn't seem to mind - I'm sure it's configurable in zsh and likely bash too)
* nicer tokens for unspecified things - group for core resources (Namespace, ServiceAccount etc), and namespace for cluster-wide resources (ClusterRoleBinding, Namespace, etc.)

Proposals to follow in individual comments so that people can give thumbs up/down, and please add any that I haven't thought of.

**Comment by willthames** [comment]
`group.Kind.namespace.name` (e.g. `apps.Deployment.test.test-deploy`)

**Comment by willthames** [comment]
`group/Kind/namespace/name` (e.g. `apps/Deployment/test/test-deploy`)

**Comment by willthames** [comment]
`group_Kind_namespace_name` (e.g. `apps_Deployment_test_test-deploy`)

**Comment by willthames** [comment]
For group/namespace-less resources: use existing `~G` and `~X`

upsides: less difference from now, so an easier change
downsides: not at all intuitive for new people

**Comment by willthames** [comment]
For group/namespace-less resources: use a character that isn't part of a valid DNS label. Preferably one that isn't a shell special character too - so `+` would be better than `*`, for example.

e.g. `+.Namespace.+.test` (if we used dots, other separators work just as well)

**Comment by willthames** [comment]
For group/namespace-less resources: use an empty value - e.g. `.Namespace..test`

con: quite hard for humans to read

**Comment by willthames** [comment]
For group/namespace-less resources: I was going to suggest using `core` for group-less resources (as I don't think it's likely to conflict now or in future), but I can't come up with a similar word for namespaces that couldn't possibly conflict (even `none` and `null` seem to be valid namespace names). Leaving this here so that at least people know why I ruled it out (and in case someone does think of a word that a namespace isn't allowed to have)

**Comment by willthames** [comment]
For group/namespace-less resources: `_` is also an illegal namespace name and quite a nice placeholder, so `_.Namespace._.test` works too (this one only works if we don't use `_` as the separator though!)

**Comment by pst** [comment]
Another aspect to consider is having a provider or data-source attribute to keep the legacy ID format, even if we make the new IDs the default, having the flag would make this a less intrusive change on existing configurations.

**Comment by pst** [comment]
I think slash makes a lot of sense, because it's already used by K8s as a divider between group and version, e.g. `apiVersion: apps/v1`. And also supported by kubectl as divider between resource and name, e.g. `kubectl get namespace/default` or `kubectl -n argocd get deployment/argocd-server`

As I said I'm supportive of making this change. But I'd like to put some effort into making it painless for existing users (e.g. the attribute to keep legacy IDs) and be careful before releasing this. I was thinking we could create a branch (breaking-changes) or something like that and initially merge all breaking changes into that.

I can then cut a final release of the provider before the breaking changes and we can make sure the breaking changes are fully tested with release-candidates before we merge them into main.

What do you think?

**Comment by willthames** [comment]
This change affects two code paths: kustomizationResourceImport and flattenKustomizeIDs  used by the kustomization data resources. 

For imports, we can just see if either new format or old format match, and handle appropriately

For the kustomization data resources, I think having a parameter that we can later remove makes most sense. While I dislike negative variable names, ignoreApiVersion might make sense.

The best strategy I can come up with for handling the breaking changes is as follows:

* 0.7.0: add a [deprecated attribute](https://www.terraform.io/docs/extend/best-practices/deprecations.html) called ignoreApiVersion, default ignoreApiVersion to false, add a note in the changelog that it will change to true in 0.8.0 and go away in 0.9.0/0.10.0/whenever
* 0.8.0: Default ignoreApiVersion to true, add api upgrade behaviour (#130), update the changelog to remove the bit about changing in 0.8.0
* 0.9.0/0.10.0/whenever: Remove ignoreApiVersion

I would like 0.7.0 to exist once I've implemented `ignoreApiVersion` to your satisfaction, and 0.8.0-alpha1/beta1/rc1 (depending on your level of confidence) to exist shortly afterwards but no need to rush on finalizing 0.8.0 for a while.

To relate your approach to the above, main becomes 0.7.0 and breaking-changes is what will be 0.8.0, eventually (some cherry-picking will be needed to keep 0.8.0 up to date as main evolves in parallel)

**Comment by willthames** [comment]
Looks like `group/Kind/namespace/name` with underscore placeholders is preferred approach (I realised later that dots as separators would be terrible as groups can and do contain dots)

**Comment by pst** [comment]
We could also call the parameter `legacy_id_format` (TF uses snake case for attributes). This would mean it's not negative. I also think it's ok to release 0.7.0 from current master.

Then, have 0.8.0 switch to the new format and have the `legacy_id_format` to allow existing users to keep using the old format. 

Optimally, we'd implement this in a way that updating the provider would create a destroy-and-recreate plan for all existing resources - which it would probably out of the box. Users that don't want to destroy and recreate can use the attribute to keep the old ID format.

I will have to do a lot of testing for the framework and catalog, but I moved to the lock file approach a few releases ago. So users are in control of their provider versions.

Regarding provider use in modules, it's probably best to have the ID format attribute be on the provider level. Because users control what provider they inject into modules and this way existing modules can use the new provider versions without requiring new module versions to expose a module variable to configure the data source in the module.

Last question, about the empty group and namespace fields. Kind and name are always required. Group is "" for some built-in resources. Namespace depends on whether namespaced is true for the Kind.

Some examples:

 * `Namespace/test` Kind and name
 * `apps/Deployment/test/test` group, Kind, namespace and name
 * `ConfigMap/test/test` Kind, namespace and name
 * `rbac.authorization.k8s.io/ClusterRoleBinding/test` group, Kind, name
 
 It may be possible, but is certainly error-prone, to not have a defined character for empty. From above it seems we both prefer underscore `_` for empty group or namespace. We may be missing something, but until then we could give it a try.
 
 Same examples with `_`:
 
 * `_/Namespace/_/test` Kind and name
 * `apps/Deployment/test/test` group, Kind, namespace and name
 * `_/ConfigMap/test/test` Kind, namespace and name
 * `rbac.authorization.k8s.io/ClusterRoleBinding/_/test` group, Kind, name
