### ISSUE TITLE
Please publish to the OpenTofu Registry

### ISSUE THREAD

**Issue by bootc** [kbst/terraform-provider-kustomization#240]
This provider is the only one I depend on that isn't available in `registry.opentofu.org`, and I would really like to be able to make the switch from HashiCorp's Terraform. Please publish the provider to the OpenTofu registry to allow people to use it with OpenTofu.

**Comment by Yantrio** [comment]
Hi @bootc and others!

Right now there is no requirement to register your provider on the OpenTofu registry, because it reads directly from github releases.

This issue is actually due to a bug in the opentofu registry. In this case, this repository does not have any releases that are not marked as pre-release. So the registry is ignoring those.

I will raise an issue to ensure that the opentofu registry supports github releases marked as pre-release now and I will have a fix for this shortly.

**Comment by Yantrio** [comment]
Hi again @bootc,

This issue has now been resolved with this PR https://github.com/opentofu/registry/pull/151 and you should be able to use this provider with OpenTofu 🎉 

Please feel free to raise issues on the OpenTofu Registry repo if you hit any other issues. For now I think we can close this issue here?

**Comment by bootc** [comment]
Thank you! 🎉 That works!
